const PROPERTIES_DATA = [
  {
    id: "1",
    title: "Modern Penthouse, VI",
    location: "Victoria Island, Lagos",
    price: 850000000,
    priceFormatted: "₦850M",
    beds: 4,
    baths: 5,
    area: 5200,
    image: "https://images.unsplash.com/photo-1512917774080-9b41033571dd?w=600&h=400&fit=crop",
    type: "Penthouse",
    description:
      "Stunning penthouse with panoramic views of Victoria Island. Features floor-to-ceiling windows, state-of-the-art finishes, and private rooftop terrace.",
  },
  {
    id: "2",
    title: "Waterfront Villa, Ikoyi",
    location: "Ikoyi, Lagos",
    price: 1200000000,
    priceFormatted: "₦1.2B",
    beds: 5,
    baths: 6,
    area: 8500,
    image: "https://images.unsplash.com/photo-1613490900233-141a8e51e183?w=600&h=400&fit=crop",
    type: "Villa",
    description: "Exquisite waterfront villa with direct beach access and infinity pool overlooking the Lagos lagoon.",
  },
  {
    id: "3",
    title: "Contemporary Estate, Lekki",
    location: "Lekki Phase 1, Lagos",
    price: 750000000,
    priceFormatted: "₦750M",
    beds: 4,
    baths: 4,
    area: 6800,
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&h=400&fit=crop",
    type: "Estate",
    description: "Striking contemporary estate in the heart of Lekki Phase 1 with cutting-edge architecture.",
  },
  {
    id: "4",
    title: "Exclusive Townhouse, Banana Island",
    location: "Banana Island, Ikoyi",
    price: 950000000,
    priceFormatted: "₦950M",
    beds: 5,
    baths: 5,
    area: 7200,
    image: "https://images.unsplash.com/photo-1600607687644-c173dbb33a83?w=600&h=400&fit=crop",
    type: "Townhouse",
    description: "Luxurious townhouse on exclusive Banana Island with private security and gated community amenities.",
  },
  {
    id: "5",
    title: "Palatial Estate, Abuja",
    location: "Asokoro, Abuja",
    price: 1100000000,
    priceFormatted: "₦1.1B",
    beds: 6,
    baths: 7,
    area: 10000,
    image: "https://images.unsplash.com/photo-1600566753376-12c8ab9c15e2?w=600&h=400&fit=crop",
    type: "Estate",
    description: "Spectacular palatial estate in Abuja's most prestigious neighborhood.",
  },
  {
    id: "6",
    title: "Luxury Penthouse, Lekki",
    location: "Lekki Conservation Centre, Lagos",
    price: 900000000,
    priceFormatted: "₦900M",
    beds: 4,
    baths: 4,
    area: 5800,
    image: "https://images.unsplash.com/photo-1522142335944-f5e1e0c74e80?w=600&h=400&fit=crop",
    type: "Penthouse",
    description: "Modern penthouse near Lekki Conservation Centre offering tranquility with urban convenience.",
  },
  {
    id: "7",
    title: "Beachfront Villa, Kribi",
    location: "Kribi Estate, Ikoyi",
    price: 1050000000,
    priceFormatted: "₦1.05B",
    beds: 5,
    baths: 5,
    area: 7500,
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop",
    type: "Villa",
    description: "Elegant beachfront villa with direct lagoon access and resort-style amenities.",
  },
  {
    id: "8",
    title: "Smart Home Estate, Ajah",
    location: "Ajah, Lagos",
    price: 680000000,
    priceFormatted: "₦680M",
    beds: 4,
    baths: 4,
    area: 5500,
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&h=400&fit=crop",
    type: "Estate",
    description: "Ultra-modern smart home with fully integrated IoT systems and state-of-the-art security.",
  },
  {
    id: "9",
    title: "Heritage Villa, Old Ikoyi",
    location: "Old Ikoyi, Lagos",
    price: 800000000,
    priceFormatted: "₦800M",
    beds: 5,
    baths: 5,
    area: 7000,
    image: "https://images.unsplash.com/photo-1600047915290-98e5dba7214d?w=600&h=400&fit=crop",
    type: "Villa",
    description: "Charming heritage villa combining classical architecture with modern amenities.",
  },
  {
    id: "10",
    title: "Ultra-Luxury Mansion, VI",
    location: "Banana Island, Victoria Island",
    price: 1400000000,
    priceFormatted: "₦1.4B",
    beds: 6,
    baths: 7,
    area: 9500,
    image: "https://images.unsplash.com/photo-1600972915901-85cf8f200a97?w=600&h=400&fit=crop",
    type: "Estate",
    description: "Ultra-luxury mansion on prestigious Banana Island featuring the finest materials.",
  },
  {
    id: "11",
    title: "Sunset View Penthouse, VI",
    location: "Victoria Island, Lagos",
    price: 920000000,
    priceFormatted: "₦920M",
    beds: 4,
    baths: 5,
    area: 5600,
    image: "https://images.unsplash.com/photo-1600573472550-8090b5e9e90b?w=600&h=400&fit=crop",
    type: "Penthouse",
    description: "Spectacular penthouse with breathtaking sunset views across Victoria Island.",
  },
]

const TESTIMONIALS_DATA = [
  {
    text: "I purchased my dream luxury home through them. Exceptional service and market expertise!",
    author: "Chioma Okonkwo",
    role: "Property Owner",
    rating: 5,
  },
  {
    text: "Professional, reliable, and extremely knowledgeable. Highly recommended for luxury properties.",
    author: "Dr. Emeka Chukwu",
    role: "Investor",
    rating: 5,
  },
  {
    text: "Their investment advisory helped me secure a premium property with excellent returns.",
    author: "Adekunle Adeleke",
    role: "Real Estate Investor",
    rating: 5,
  },
  {
    text: "Outstanding service! Helped me navigate the entire property acquisition process smoothly.",
    author: "Inioluwa Ayeni",
    role: "Property Buyer",
    rating: 5,
  },
  {
    text: "The best real estate experience I've ever had. Highly professional and trustworthy.",
    author: "Folake Olatunde",
    role: "Premium Client",
    rating: 5,
  },
  {
    text: "Exceptional portfolio and market knowledge. This is who you want handling your investments!",
    author: "Tunde Ogunlade",
    role: "Investor",
    rating: 5,
  },
]
