export interface Property {
  id: string
  title: string
  location: string
  price: number
  priceFormatted: string
  beds: number
  baths: number
  area: number
  image: string
  images: string[]
  description: string
  features: string[]
  yearBuilt: number
  type: "Villa" | "Penthouse" | "Estate" | "Townhouse"
}

export const propertiesData: Property[] = [
  {
    id: "1",
    title: "Modern Penthouse, VI",
    location: "Victoria Island, Lagos",
    price: 850000000,
    priceFormatted: "₦850M",
    beds: 4,
    baths: 5,
    area: 5200,
    image: "/modern-luxury-penthouse-view.jpg",
    images: ["/modern-luxury-penthouse-view.jpg", "/luxury-penthouse-interior.jpg", "/modern-apartment-kitchen.jpg"],
    type: "Penthouse",
    description:
      "Stunning penthouse with panoramic views of Victoria Island. Features floor-to-ceiling windows, state-of-the-art finishes, and private rooftop terrace. Perfect for the discerning buyer seeking contemporary luxury.",
    features: [
      "Panoramic City Views",
      "Private Rooftop Terrace",
      "Smart Home Automation",
      "Private Elevator Access",
      "Wine Cellar",
      "Home Cinema",
      "Gym & Spa",
    ],
    yearBuilt: 2022,
  },
  {
    id: "2",
    title: "Waterfront Villa, Ikoyi",
    location: "Ikoyi, Lagos",
    price: 1200000000,
    priceFormatted: "₦1.2B",
    beds: 5,
    baths: 6,
    area: 8500,
    image: "/luxury-villa-waterfront-pool.jpg",
    images: ["/luxury-villa-waterfront-pool.jpg", "/luxury-villa-exterior.jpg", "/infinity-pool-ocean-view.jpg"],
    type: "Villa",
    description:
      "Exquisite waterfront villa with direct beach access and infinity pool overlooking the Lagos lagoon. This architectural masterpiece features luxury finishes throughout and serves as the ultimate entertainment venue.",
    features: [
      "Direct Beach Access",
      "Infinity Pool",
      "Wine Cellar",
      "Chef's Kitchen",
      "Guest House",
      "Home Theater",
      "Boat Dock",
      "Security Gates",
    ],
    yearBuilt: 2020,
  },
  {
    id: "3",
    title: "Contemporary Estate, Lekki",
    location: "Lekki Phase 1, Lagos",
    price: 750000000,
    priceFormatted: "₦750M",
    beds: 4,
    baths: 4,
    area: 6800,
    image: "/contemporary-estate-architecture.jpg",
    images: ["/contemporary-estate-architecture.jpg", "/modern-estate-gardens.jpg", "/luxury-home-living-room.jpg"],
    type: "Estate",
    description:
      "Striking contemporary estate in the heart of Lekki Phase 1. Features cutting-edge architecture, lush landscaped gardens, and premium security. An ideal residence for families seeking modern elegance.",
    features: [
      "Smart Home System",
      "Landscaped Gardens",
      "Swimming Pool",
      "Tennis Court",
      "3-Car Garage",
      "Security House",
      "Water Treatment",
      "Solar Panels",
    ],
    yearBuilt: 2021,
  },
  {
    id: "4",
    title: "Exclusive Townhouse, Banana Island",
    location: "Banana Island, Ikoyi",
    price: 950000000,
    priceFormatted: "₦950M",
    beds: 5,
    baths: 5,
    area: 7200,
    image: "/luxury-townhouse-exterior.jpg",
    images: ["/luxury-townhouse-exterior.jpg", "/modern-townhouse-interior.jpg", "/luxury-bedroom-suite.jpg"],
    type: "Townhouse",
    description:
      "Luxurious townhouse on exclusive Banana Island with private security and gated community amenities. Features premium finishes and close proximity to Lagos' finest dining and entertainment.",
    features: [
      "Gated Community",
      "Private Security",
      "Rooftop Garden",
      "Home Office",
      "Sauna & Steam Room",
      "Elevator",
      "Parking",
      "Community Pool",
    ],
    yearBuilt: 2023,
  },
  {
    id: "5",
    title: "Palatial Estate, Abuja",
    location: "Asokoro, Abuja",
    price: 1100000000,
    priceFormatted: "₦1.1B",
    beds: 6,
    baths: 7,
    area: 10000,
    image: "/luxury-abuja-mansion.jpg",
    images: ["/luxury-abuja-mansion.jpg", "/palatial-estate-grounds.jpg", "/luxury-dining-hall.jpg"],
    type: "Estate",
    description:
      "Spectacular palatial estate in Abuja's most prestigious neighborhood. Situated on extensive grounds with comprehensive amenities and state-of-the-art technology throughout.",
    features: [
      "Extensive Grounds",
      "Olympic Pool",
      "Home Automation",
      "Guest Wing",
      "Theater Hall",
      "Gym & Spa",
      "Helipad",
      "Premium Security",
    ],
    yearBuilt: 2019,
  },
  {
    id: "6",
    title: "Luxury Penthouse, Lekki",
    location: "Lekki Conservation Centre, Lagos",
    price: 900000000,
    priceFormatted: "₦900M",
    beds: 4,
    baths: 4,
    area: 5800,
    image: "/modern-lekki-penthouse.jpg",
    images: ["/modern-lekki-penthouse.jpg", "/penthouse-balcony-view.jpg", "/luxury-master-suite.jpg"],
    type: "Penthouse",
    description:
      "Modern penthouse near Lekki Conservation Centre offering tranquility with urban convenience. Premium finishes, private elevator, and spectacular city views.",
    features: [
      "Private Elevator",
      "Rooftop Bar",
      "Smart Automation",
      "Maid's Quarters",
      "Study Room",
      "Walk-in Closets",
      "Laundry Room",
      "Premium Finishes",
    ],
    yearBuilt: 2022,
  },
  {
    id: "7",
    title: "Beachfront Villa, Kribi",
    location: "Kribi Estate, Ikoyi",
    price: 1050000000,
    priceFormatted: "₦1.05B",
    beds: 5,
    baths: 5,
    area: 7500,
    image: "/beachfront-villa-sunset.jpg",
    images: ["/beachfront-villa-sunset.jpg", "/luxury-villa-exterior.jpg", "/infinity-pool-ocean-view.jpg"],
    type: "Villa",
    description:
      "Elegant beachfront villa with direct lagoon access. Tropical paradise featuring resort-style amenities and sophisticated entertainment spaces.",
    features: [
      "Direct Beach Access",
      "Resort Pool",
      "Beach Bar",
      "Spa Facilities",
      "Guest House",
      "Sunset Deck",
      "Private Jetty",
      "Security Gates",
    ],
    yearBuilt: 2021,
  },
  {
    id: "8",
    title: "Smart Home Estate, Ajah",
    location: "Ajah, Lagos",
    price: 680000000,
    priceFormatted: "₦680M",
    beds: 4,
    baths: 4,
    area: 5500,
    image: "/contemporary-estate-architecture.jpg",
    images: ["/contemporary-estate-architecture.jpg", "/modern-estate-gardens.jpg", "/luxury-home-living-room.jpg"],
    type: "Estate",
    description:
      "Ultra-modern smart home with fully integrated IoT systems. State-of-the-art security, energy management, and entertainment technology.",
    features: [
      "Full Home Automation",
      "CCTV Security System",
      "Solar Power System",
      "Smart Lighting",
      "Digital Locks",
      "Home Theater",
      "Backup Generator",
      "Premium Finishes",
    ],
    yearBuilt: 2023,
  },
  {
    id: "9",
    title: "Heritage Villa, Old Ikoyi",
    location: "Old Ikoyi, Lagos",
    price: 800000000,
    priceFormatted: "₦800M",
    beds: 5,
    baths: 5,
    area: 7000,
    image: "/luxury-villa-exterior.jpg",
    images: ["/luxury-villa-exterior.jpg", "/modern-estate-gardens.jpg", "/luxury-home-living-room.jpg"],
    type: "Villa",
    description:
      "Charming heritage villa in the historic Old Ikoyi area. Combines classical architecture with modern amenities in a secure, established neighborhood.",
    features: [
      "High Ceilings",
      "Ornate Finishes",
      "Private Garden",
      "Tennis Court",
      "Swimming Pool",
      "Guest Wing",
      "Security Gates",
      "Mature Trees",
    ],
    yearBuilt: 2018,
  },
  {
    id: "10",
    title: "Ultra-Luxury Mansion, VI",
    location: "Banana Island, Victoria Island",
    price: 1400000000,
    priceFormatted: "₦1.4B",
    beds: 6,
    baths: 7,
    area: 9500,
    image: "/luxury-home-living-room.jpg",
    images: ["/luxury-home-living-room.jpg", "/infinity-pool-ocean-view.jpg", "/luxury-villa-waterfront-pool.jpg"],
    type: "Estate",
    description:
      "Ultra-luxury mansion on prestigious Banana Island. This architectural marvel features the finest materials and craftsmanship with world-class amenities.",
    features: [
      "Grand Foyer",
      "Ballroom",
      "Wine Cellar",
      "Olympic Pool",
      "Home Theater",
      "Spa & Sauna",
      "Helipad",
      "Premium Security",
    ],
    yearBuilt: 2020,
  },
  {
    id: "11",
    title: "Sunset View Penthouse, VI",
    location: "Victoria Island, Lagos",
    price: 920000000,
    priceFormatted: "₦920M",
    beds: 4,
    baths: 5,
    area: 5600,
    image: "/modern-luxury-penthouse-view.jpg",
    images: ["/modern-luxury-penthouse-view.jpg", "/luxury-penthouse-interior.jpg", "/modern-apartment-kitchen.jpg"],
    type: "Penthouse",
    description:
      "Spectacular penthouse with breathtaking sunset views across Victoria Island. Features premium finishes, private wine bar, and exclusive rooftop amenities.",
    features: [
      "Sunset Terrace",
      "Private Wine Bar",
      "Smart Automation",
      "Maid's Quarters",
      "Home Cinema",
      "Gym",
      "Private Elevator",
      "Concierge Service",
    ],
    yearBuilt: 2023,
  },
]
